# fly.toml app configuration file generated for ibis on 2024-08-09T09:45:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ibis'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.22.5'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = 'bash -l -c "migrate -verbose -source file://migrations -database $DATABASE_URL up"'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
